// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortSentinel.Infrastructure.Persistence;

#nullable disable

namespace PortSentinel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SentinelDbContext))]
    [Migration("20260930165804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PortSentinel.Domain.AccessRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorSid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Allowed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegisteredDeviceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredDeviceId")
                        .IsUnique();

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("PortSentinel.Domain.ApplicationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScanIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RetentionDays = 30,
                            ScanIntervalSeconds = 10
                        });
                });

            modelBuilder.Entity("PortSentinel.Domain.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorSid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("OccurredUtc");

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("PortSentinel.Domain.DeviceConnectionEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysicalInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredUtc");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("PortSentinel.Domain.PolicyRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredPolicyJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerifiedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Revisions");
                });

            modelBuilder.Entity("PortSentinel.Domain.RegisteredDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdentityKey")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("PortSentinel.Domain.AccessRule", b =>
                {
                    b.HasOne("PortSentinel.Domain.RegisteredDevice", null)
                        .WithOne()
                        .HasForeignKey("PortSentinel.Domain.AccessRule", "RegisteredDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PortSentinel.Domain.RegisteredDevice", b =>
                {
                    b.OwnsOne("PortSentinel.Domain.DeviceIdentity", "Identity", b1 =>
                        {
                            b1.Property<Guid>("RegisteredDeviceId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("HasUniqueId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsSystemDisk")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsUsbStorage")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("PhysicalInstanceId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ProductId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("SerialNumber")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("VendorId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("RegisteredDeviceId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("RegisteredDeviceId");
                        });

                    b.Navigation("Identity")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
